# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-06 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('checkin', models.DateTimeField()),
                ('checkout', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('Room', models.IntegerField(default=0)),
                ('Room_Types', models.CharField(choices=[(b'St', b'Standared'), (b'Tw', b'Twin'), (b'Dx', b'Deluxe'), (b'Su', b'Suit')], default=b'St', max_length=2)),
            ],
        ),
    ]
