# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-14 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Room_Types',
            field=models.CharField(choices=[(b'Standared', b'Standared'), (b'Twin', b'Twin'), (b'Deluxe', b'Deluxe'), (b'Suit', b'Suit')], default=b'Standared', max_length=200),
        ),
    ]
