# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-12 12:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20160712_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 12, 12, 39, 22, 850000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 12, 12, 39, 22, 850000, tzinfo=utc)),
        ),
    ]
