# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-19 08:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20160712_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 19, 8, 29, 55, 847000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 19, 8, 29, 55, 847000, tzinfo=utc)),
        ),
    ]
